"""add_status_rejection_reason_to_timesheets

Revision ID: 00aa6a33b392
Revises: '4b8d19e3a44f'
Create Date: 2026-08-12 15:23:43.362785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00aa6a33b392'
down_revision: Union[str, None] = '4b8d19e3a44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('status', sa.String(length=20), server_default='draft', nullable=False))
    op.add_column('timesheets', sa.Column('rejection_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_timesheets_status'), 'timesheets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheets_status'), table_name='timesheets')
    op.drop_column('timesheets', 'rejection_reason')
    op.drop_column('timesheets', 'status')
    # ### end Alembic commands ###
