"""Add is_active to project_assignments

Revision ID: 0ce5b039fb8c
Revises: 'ad7a7f38850f'
Create Date: 2026-08-11 15:51:19.442518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce5b039fb8c'
down_revision: Union[str, None] = 'ad7a7f38850f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_assignments', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_assignments', 'is_active')
    # ### end Alembic commands ###
