"""Add missing columns to leave_types

Revision ID: 1d525d8bb4da
Revises: '74c644074dd3'
Create Date: 2026-08-24 10:54:54.238168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d525d8bb4da'
down_revision: Union[str, None] = '74c644074dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_types', sa.Column('allocated_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_types', 'allocated_hours')
    # ### end Alembic commands ###
