"""Add type, description, is_mandatory to holidays

Revision ID: 4b8d19e3a44f
Revises: '0ce5b039fb8c'
Create Date: 2026-08-12 12:54:52.407756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b8d19e3a44f'
down_revision: Union[str, None] = '0ce5b039fb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holidays', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('holidays', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('holidays', sa.Column('is_mandatory', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holidays', 'is_mandatory')
    op.drop_column('holidays', 'description')
    op.drop_column('holidays', 'type')
    # ### end Alembic commands ###
