"""add_working_calendar

Revision ID: 74c644074dd3
Revises: 'ec51fed01055'
Create Date: 2026-08-13 11:56:02.842563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c644074dd3'
down_revision: Union[str, None] = 'ec51fed01055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('working_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_day_hours', sa.Float(), nullable=False),
    sa.Column('half_day_hours', sa.Float(), nullable=False),
    sa.Column('partial_day_min_hours', sa.Float(), nullable=False),
    sa.Column('partial_day_max_hours', sa.Float(), nullable=False),
    sa.Column('working_days', sa.JSON(), nullable=False),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_calendar_id'), 'working_calendar', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_working_calendar_id'), table_name='working_calendar')
    op.drop_table('working_calendar')
    # ### end Alembic commands ###
