"""shift_tools_to_milestone

Revision ID: 83ef1e1d3fd5
Revises: 'a1b2c3d4e5f6'
Create Date: 2026-09-09 13:28:20.327905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ef1e1d3fd5'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.execute('TRUNCATE TABLE tool_allocations CASCADE')
    op.add_column('tool_allocations', sa.Column('milestone_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tool_allocations_milestone_id'), 'tool_allocations', ['milestone_id'], unique=False)
    op.drop_constraint(op.f('tool_allocations_project_id_fkey'), 'tool_allocations', type_='foreignkey')
    op.create_foreign_key(None, 'tool_allocations', 'milestones', ['milestone_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tool_allocations', 'project_id')
    op.drop_constraint(op.f('fk_users_department_id'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_department_id'), 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('tool_allocations', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tool_allocations', type_='foreignkey')
    op.create_foreign_key(op.f('tool_allocations_project_id_fkey'), 'tool_allocations', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_tool_allocations_milestone_id'), table_name='tool_allocations')
    op.drop_column('tool_allocations', 'milestone_id')
    op.alter_column('projects', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
