"""Unified timesheets

Revision ID: 996045d4497e
Revises: '00aa6a33b392'
Create Date: 2026-08-12 16:42:51.874399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996045d4497e'
down_revision: Union[str, None] = '00aa6a33b392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('billable_hours', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('timesheets', sa.Column('billable_work_summary', sa.Text(), nullable=True))
    op.add_column('timesheets', sa.Column('non_billable_hours', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('timesheets', sa.Column('non_billable_work_summary', sa.Text(), nullable=True))

    # --- DATA MIGRATION ---
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT id, user_id, project_assignment_id, timesheet_date, hours, is_billable, task_description, work_summary, status
        FROM timesheets
    """))
    rows = result.fetchall()
    
    groups = {}
    for row in rows:
        key = (row.user_id, row.project_assignment_id, row.timesheet_date)
        if key not in groups:
            groups[key] = []
        groups[key].append(row)
        
    status_priority = {'approved': 4, 'pending': 3, 'rejected': 2, 'draft': 1}
    
    for key, group_rows in groups.items():
        group_rows.sort(key=lambda r: status_priority.get(r.status, 0), reverse=True)
        primary_row = group_rows[0]
        
        b_hours = 0.0
        nb_hours = 0.0
        b_summary_parts = []
        nb_summary_parts = []
        
        for r in group_rows:
            combined_desc = r.work_summary
            if r.task_description:
                combined_desc = f"{r.task_description} | {combined_desc}"
                
            if r.is_billable:
                b_hours += r.hours
                b_summary_parts.append(combined_desc)
            else:
                nb_hours += r.hours
                nb_summary_parts.append(combined_desc)
                
        b_summary = " & ".join(b_summary_parts) if b_summary_parts else None
        nb_summary = " & ".join(nb_summary_parts) if nb_summary_parts else None
        
        connection.execute(sa.text("""
            UPDATE timesheets 
            SET billable_hours = :b_hours, 
                billable_work_summary = :b_summary,
                non_billable_hours = :nb_hours,
                non_billable_work_summary = :nb_summary,
                status = :status
            WHERE id = :id
        """), {
            "b_hours": b_hours,
            "b_summary": b_summary,
            "nb_hours": nb_hours,
            "nb_summary": nb_summary,
            "status": primary_row.status,
            "id": primary_row.id
        })
        
        other_ids = [r.id for r in group_rows[1:]]
        if other_ids:
            connection.execute(sa.text("""
                DELETE FROM timesheets WHERE id = ANY(:ids)
            """), {"ids": other_ids})
    # --- END DATA MIGRATION ---
    op.create_unique_constraint('uq_user_project_date', 'timesheets', ['user_id', 'project_assignment_id', 'timesheet_date'])
    op.drop_column('timesheets', 'is_billable')
    op.drop_column('timesheets', 'hours')
    op.drop_column('timesheets', 'task_description')
    op.drop_column('timesheets', 'work_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('work_summary', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('timesheets', sa.Column('task_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('timesheets', sa.Column('hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('timesheets', sa.Column('is_billable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_project_date', 'timesheets', type_='unique')
    op.drop_column('timesheets', 'non_billable_work_summary')
    op.drop_column('timesheets', 'non_billable_hours')
    op.drop_column('timesheets', 'billable_work_summary')
    op.drop_column('timesheets', 'billable_hours')
    # ### end Alembic commands ###
