"""Add is_active to Client and Project models

Revision ID: ad7a7f38850f
Revises: 'f0e16dba4eea'
Create Date: 2026-08-11 11:42:14.548780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7a7f38850f'
down_revision: Union[str, None] = 'f0e16dba4eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('projects', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_active')
    op.drop_column('clients', 'is_active')
    # ### end Alembic commands ###
