"""Add CTC and milestone budgets

Revision ID: b00df7937f2e
Revises: 'a7ae05683e83'
Create Date: 2026-09-01 17:14:53.347559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00df7937f2e'
down_revision: Union[str, None] = 'a7ae05683e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milestone_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('milestone_id', 'user_id', name='uq_milestone_user_assignment')
    )
    op.create_index(op.f('ix_milestone_assignments_id'), 'milestone_assignments', ['id'], unique=False)
    op.add_column('milestones', sa.Column('budget', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('ctc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ctc')
    op.drop_column('milestones', 'budget')
    op.drop_index(op.f('ix_milestone_assignments_id'), table_name='milestone_assignments')
    op.drop_table('milestone_assignments')
    # ### end Alembic commands ###
