"""add_notifications_cleared_at

Revision ID: c05bdb83aee9
Revises: '1d525d8bb4da'
Create Date: 2026-08-24 11:05:36.368969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05bdb83aee9'
down_revision: Union[str, None] = '1d525d8bb4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications_cleared_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_cleared_at')
    # ### end Alembic commands ###
