"""Remove approval workflow

Revision ID: d32129ba8c5e
Revises: '996045d4497e'
Create Date: 2026-08-12 17:04:54.590294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32129ba8c5e'
down_revision: Union[str, None] = '996045d4497e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # --- DATA MIGRATION ---
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE timesheets SET status = 'submitted'"))
    # --- END DATA MIGRATION ---
    op.drop_column('timesheets', 'rejection_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timesheets', sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
