"""Add completion_percentage and actual_start_date to milestones

Revision ID: e1c9905d4158
Revises: 'b00df7937f2e'
Create Date: 2026-09-02 10:51:53.173479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c9905d4158'
down_revision: Union[str, None] = 'b00df7937f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestones', sa.Column('completion_percentage', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('milestones', sa.Column('actual_start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestones', 'actual_start_date')
    op.drop_column('milestones', 'completion_percentage')
    # ### end Alembic commands ###
