"""add_leave_type_config_fields

Revision ID: ec51fed01055
Revises: 'd32129ba8c5e'
Create Date: 2026-08-12 17:43:22.367846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec51fed01055'
down_revision: Union[str, None] = 'd32129ba8c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_types', sa.Column('code', sa.String(length=10), nullable=False))
    op.add_column('leave_types', sa.Column('days_per_year', sa.Integer(), nullable=False))
    op.add_column('leave_types', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('leave_types', sa.Column('requires_document', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_leave_types_code'), 'leave_types', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_types_code'), table_name='leave_types')
    op.drop_column('leave_types', 'requires_document')
    op.drop_column('leave_types', 'is_paid')
    op.drop_column('leave_types', 'days_per_year')
    op.drop_column('leave_types', 'code')
    # ### end Alembic commands ###
